--1
SELECT a.TITLE FROM MC_ARTWORK a
INNER JOIN MC_LOCATION l
ON l.LOCATION_ID = a.CURRENT_LOC
WHERE l.NAME = 'Gallery A';

--2
SELECT * FROM MC_EXHIBITION e
INNER JOIN MC_ARTWORK_EXH ae ON e.EXHIBITION_ID = ae.EXHIBITION_ID
INNER JOIN MC_ARTWORK a ON ae.ARTWORK_ID = a.ARTWORK_ID
WHERE a.EST_VALUE = 
    (SELECT sum(EST_VALUE) FROM MC_ARTWORK a
    INNER JOIN MC_ARTWORK_EXH b USING (ARTWORK_ID)
    GROUP BY b.EXHIBITION_ID
    HAVING SUM(EST_VALUE) > 100000000);
    
--3
SELECT ARTWORK_ID, TITLE, ROUND((EST_VALUE/5), 2) AS ANNUAL_INSURED_VALUE
FROM MC_ARTWORK;

--4
SELECT a.FULL_NAME, aw.TITLE AS ARTWORK_TITLE
FROM MC_ARTIST a
INNER JOIN MC_ARTWORK aw ON a.ARTIST_ID = aw.ARTIST_ID
INNER JOIN MC_ARTWORK_EXH ae ON ae.ARTWORK_ID = aw.ARTWORK_ID
INNER JOIN MC_EXHIBITION e ON e.EXHIBITION_ID = ae.EXHIBITION_ID
WHERE e.TITLE IN ('Modern Voices')
ORDER BY a.FULL_NAME;

--5
SELECT aw.TITLE FROM MC_ARTWORK aw
INNER JOIN MC_COLLECTION c ON aw.COLLECTION_ID = c.COLLECTION_ID
WHERE EST_VALUE > (SELECT AVG(aw2.EST_VALUE) FROM MC_ARTWORK aw2
                   INNER JOIN MC_COLLECTION c2 ON c2.COLLECTION_ID = aw2.COLLECTION_ID
                   GROUP BY c2.COLLECTION_ID, c2.TITLE
                   HAVING c2.COLLECTION_ID = 10) 
AND c.COLLECTION_ID = 10;

--6
SELECT * FROM MC_EXHIBITION
WHERE (END_DATE - START_DATE) = (SELECT MIN(END_DATE - START_DATE) FROM MC_EXHIBITION);

--7
SELECT aw.TITLE AS ARTWORK_TITLE, l.NAME AS LOCATION
FROM MC_ARTWORK aw
INNER JOIN MC_LOCATION l ON l.LOCATION_ID = aw.CURRENT_LOC
INNER JOIN MC_ARTWORK_EXH ae ON ae.ARTWORK_ID = aw.ARTWORK_ID
INNER JOIN MC_EXHIBITION e ON ae.EXHIBITION_ID = e.EXHIBITION_ID
WHERE e.EXHIBITION_ID = 3001;

--8
SELECT aw.TITLE, ae.LABEL_TEXT
FROM MC_ARTWORK aw
INNER JOIN MC_ARTWORK_EXH ae USING (ARTWORK_ID)
INNER JOIN MC_EXHIBITION e USING (EXHIBITION_ID)
INNER JOIN MC_CURATOR cu USING (CURATOR_ID)
WHERE cu.FULL_NAME LIKE '%Maria%' AND cu.FULL_NAME LIKE '%Pappas%'
ORDER BY aw.TITLE;

--9
CREATE VIEW MIDTERM_VIEW AS
SELECT ex.EXHIBITION_ID, ex.TITLE AS EXHIBITION_TITLE, aw.ARTWORK_ID, aw.TITLE AS ARTWORK_TITLE
FROM MC_ARTWORK aw
INNER JOIN MC_ARTWORK_EXH ae ON ae.ARTWORK_ID = aw.ARTWORK_ID
INNER JOIN MC_EXHIBITION ex ON ex.EXHIBITION_ID = ae.EXHIBITION_ID;

--10
SELECT COUNT(EXHIBITION_ID) AS "NO. OF EXH" FROM MIDTERM_VIEW
WHERE ARTWORK_ID = 1001
GROUP BY EXHIBITION_ID;

